module Api
  module V3
    class PuppetclassesController < V2::PuppetclassesController

      include Api::Version3

      def index
        values   = Puppetclass.authorized(:view_puppetclasses).search_for(*search_options) unless nested_obj
        values ||= case nested_obj
                     when Host::Base, Hostgroup
                       #NOTE: no search_for on array generated by all_puppetclasses
                       nested_obj.all_puppetclasses
                     else
                       nested_obj.puppetclasses.search_for(*search_options)
                   end
        @puppetclasses = values
        render :json => @puppetclasses, :each_serializer => PuppetclassSerializer
      end

      def show
        render :json => @puppetclass, :serializer => PuppetclassSerializer
      end

    end
  end
end
